export const badges = {
    "ASP.NET": "https://img.shields.io/badge/ASP.NET-5C2D91?style=for-the-badge&logo=dot-net&logoColor=white",
    "C#": "https://img.shields.io/badge/C%23-239120?style=for-the-badge&logo=c-sharp&logoColor=white",
    "MySQL": "https://img.shields.io/badge/MySQL-00000F?style=for-the-badge&logo=mysql&logoColor=white",
    "PHP": "https://img.shields.io/badge/PHP-777BB4?style=for-the-badge&logo=php&logoColor=white",
    "HTML/CSS": "https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white",
    "JavaScript": "https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black",
    "Drupal": "https://img.shields.io/badge/Drupal-0678BE?style=for-the-badge&logo=drupal&logoColor=white",
    "Facebook API": "https://img.shields.io/badge/Facebook-1877F2?style=for-the-badge&logo=facebook&logoColor=white",
    "Twitter API": "https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white",
    "Testing": "https://img.shields.io/badge/Testing-9E9E9E?style=for-the-badge&logo=test-automation&logoColor=white",
    "Teamwork": "https://img.shields.io/badge/Teamwork-FFC300?style=for-the-badge&logo=teamwork&logoColor=black",
    "Web Services": "https://img.shields.io/badge/Web_Services-0078D7?style=for-the-badge&logo=web-services&logoColor=white",
    "Software Development": "https://img.shields.io/badge/Software_Development-0078D7?style=for-the-badge&logo=software-development&logoColor=white",
    "Modo": "https://img.shields.io/badge/Modo-FFA500?style=for-the-badge&logo=modo&logoColor=white",
    "Back-End Web Development": "https://img.shields.io/badge/Back_End_Web_Development-4CAF50?style=for-the-badge&logo=back-end-web-development&logoColor=white",
    "REST APIs": "https://img.shields.io/badge/REST_APIs-4CAF50?style=for-the-badge&logo=rest-apis&logoColor=white",
    ".NET Framework": "https://img.shields.io/badge/.NET_Framework-512BD4?style=for-the-badge&logo=dotnet&logoColor=white",
    "Software Design": "https://img.shields.io/badge/Software_Design-0078D7?style=for-the-badge&logo=software-design&logoColor=white",
    "Java": "https://img.shields.io/badge/Java-007396?style=for-the-badge&logo=java&logoColor=white",
    "Python": "https://img.shields.io/badge/Python-3776AB?style=for-the-badge&logo=python&logoColor=white",
    "Teaching": "https://img.shields.io/badge/Teaching-0078D7?style=for-the-badge&logo=education&logoColor=white",
    "Algorithms": "https://img.shields.io/badge/Algorithms-4CAF50?style=for-the-badge&logo=algorithms&logoColor=white",
    "Data Structures": "https://img.shields.io/badge/Data_Structures-FFA500?style=for-the-badge&logo=data-structures&logoColor=white",
    "Problem Solving": "https://img.shields.io/badge/Problem_Solving-FFC300?style=for-the-badge&logo=problem-solving&logoColor=black",
    "Communication": "https://img.shields.io/badge/Communication-9E9E9E?style=for-the-badge&logo=communication&logoColor=white",
    "Big O Notation": "https://img.shields.io/badge/Big_O_Notation-4CAF50?style=for-the-badge&logo=math&logoColor=white",
    "Graph Algorithms": "https://img.shields.io/badge/Graph_Algorithms-FF6F00?style=for-the-badge&logo=graph&logoColor=white",
    "Dynamic Programming": "https://img.shields.io/badge/Dynamic_Programming-008080?style=for-the-badge&logo=dynamic-programming&logoColor=white",
    "Recurrence Relations": "https://img.shields.io/badge/Recurrence_Relations-FFD700?style=for-the-badge&logo=recurrence&logoColor=black",
    "Algorithm Analysis": "https://img.shields.io/badge/Algorithm_Analysis-4CAF50?style=for-the-badge&logo=math&logoColor=white",
    "Algorithm Optimization": "https://img.shields.io/badge/Algorithm_Optimization-FF6F00?style=for-the-badge&logo=optimization&logoColor=white",
    "Full-Stack Development": "https://img.shields.io/badge/Full_Stack_Development-4CAF50?style=for-the-badge&logo=development&logoColor=white",
    "Google Cloud Platform (GCP)": "https://img.shields.io/badge/Google_Cloud-4285F4?style=for-the-badge&logo=google-cloud&logoColor=white",
    "Spring Boot": "https://img.shields.io/badge/Spring_Boot-6DB33F?style=for-the-badge&logo=spring&logoColor=white",
    "API Integration": "https://img.shields.io/badge/API_Integration-FF6F00?style=for-the-badge&logo=api&logoColor=white",
    "UI/UX Design": "https://img.shields.io/badge/UI/UX_Design-512BD4?style=for-the-badge&logo=design&logoColor=white",
    "Agile Development": "https://img.shields.io/badge/Agile_Development-FF5733?style=for-the-badge&logo=agile&logoColor=white",
    "Cloud Services": "https://img.shields.io/badge/Cloud_Services-1E88E5?style=for-the-badge&logo=cloud&logoColor=white",
  };